version: '3'

services:

  node-exporter:
    image: prom/node-exporter
    container_name: kira-node-exporter
    restart: always
    ports:
      - 9100:9100

  viewer:
    build: .
    network_mode: host
    container_name: kira-viewer
    restart: always
    env_file:
      - settings.env
    depends_on:
      - node-exporter